name: Atualizar players online

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar site
        run: |
          curl -L \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -o online.html \
            https://arcanum74.com/community/players-online

      - name: Enviar para VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "online.html"
          target: "/home/kustebot_warcanum/data"
